export const GLOBAL_LOCK_OFFSET = 0;
export const INITIAL_ENTRY_POINTER_TO_POINTER =
  GLOBAL_LOCK_OFFSET + Uint32Array.BYTES_PER_ELEMENT;

export const ENDIANNESS_FLAG_POINTER =
  INITIAL_ENTRY_POINTER_TO_POINTER + Uint32Array.BYTES_PER_ELEMENT;

export enum ENDIANNESS {
  BIG,
  LITTLE,
}

export const TEMP_SAVE_POINTER =
  ENDIANNESS_FLAG_POINTER + Uint32Array.BYTES_PER_ELEMENT;

export const INITIAL_ENTRY_POINTER_VALUE =
  TEMP_SAVE_POINTER + Uint32Array.BYTES_PER_ELEMENT;

export const MEM_POOL_START =
  INITIAL_ENTRY_POINTER_VALUE + Uint32Array.BYTES_PER_ELEMENT;

export const UNDEFINED_KNOWN_ADDRESS = 0;
export const NULL_KNOWN_ADDRESS = 1;
export const TRUE_KNOWN_ADDRESS = 2;
export const FALSE_KNOWN_ADDRESS = 3;
export const MAX_64_BIG_INT = BigInt("0xFFFFFFFFFFFFFFFF");
