export const GET_UNDERLYING_ARRAY_BUFFER_SYMBOL = Symbol(
  "GET_UNDERLYING_ARRAY_BUFFER_SYMBOL"
);

export const GET_UNDERLYING_POINTER_SYMBOL = Symbol(
  "GET_UNDERLYING_POINTER_SYMBOL"
);

export const REPLACE_DATA_VIEW_SYMBOL = Symbol("REPLACE_DATA_VIEW_SYMBOL");

export const INTERNAL_API_SYMBOL = Symbol("INTERNAL_API");
