# https://github.com/rhysd/github-action-benchmark/blob/master/.github/workflows/benchmarkjs.yml
name: Benchmark

on: ["pull_request"]

jobs:
  benchmark:
    name: Run JavaScript benchmark
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [14, 15]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.OS }}-build

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: build
        run: yarn build
        shell: bash

      - name: Run benchmark
        run: node --max-old-space-size=6144 benchmarks/main-register-ts-node.js | tee benchmarks/output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: benchmarkjs, node ${{ matrix.node }}
          tool: "benchmarkjs"
          output-file-path: benchmarks/output.txt
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "110%"
          comment-always: ${{ matrix.node == 14 }}
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@bnaya"
