name: General Validity

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.OS }}-build

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: Lint
        run: yarn lint
        shell: bash

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.OS }}-build

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: test + coverage
        run: yarn test-coverage
        shell: bash

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        # env:
        # NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}

  build:
    runs-on: ubuntu-18.04
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.OS }}-build

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: build
        run: yarn build
        shell: bash
