name: General Validity

on: ["push","pull_request"]
# on: ["pull_request"]

jobs:
  test_and_validate:

    runs-on: ubuntu-18.04
  # runs-on: ${{ matrix.os }}
  # strategy:
  #   matrix:
  #     os: [ubuntu-16.04, ubuntu-18.04]
  #     node: [10, 12]

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: yarn install
      run: yarn
      shell: bash

    - name: Lint
      run: yarn lint
      shell: bash

    - name: test + coverage
      run: yarn test-coverage
      shell: bash

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      # env:
        # NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.github_token }}

    - name: build
      run: yarn build
      shell: bash
