name: General Validity

on: ["push"]

jobs:
  static-code-validation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: corepack enable

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: Static code validation
        run: yarn static-code-validation
        shell: bash

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: test + coverage
        run: yarn test-coverage
        shell: bash

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        # env:
        # NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}

  build:
    runs-on: ubuntu-24.04
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: corepack enable

      - name: yarn install
        run: yarn --immutable
        shell: bash

      - name: build
        run: yarn build
        shell: bash
